package View;

import Controller.ClientesJpaController;
import Controller.FacturaJpaController;
import Controller.ProductoVentaJpaController;
import Controller.ProductosJpaController;

import Logic.Categorias;
import Logic.Clientes;
import Logic.Factura;
import Logic.ProductoVenta;
import Logic.Productos;
import Logic.Usuario;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isaac Tu papi bello
 */
public class Form_Factura extends javax.swing.JDialog {

    private FacturaJpaController cf;
    private ProductoVentaJpaController cp;
    private Categorias cat;
    private Factura fr;
    private Factura facbus;
    private Usuario usu;
    private Clientes cl;
    private ClientesJpaController control;
    private Factura n;
    private Productos pr;
    private ProductosJpaController conp;
    private ArrayList vector;

    /**
     * Creates new form Form_productos
     */
    public Form_Factura(java.awt.Frame parent, boolean modal, Usuario u) {
        super(parent, modal);
        initComponents();
        vector = new ArrayList();
        this.setTitle("Registro de Factura");
        this.setLocationRelativeTo(null);
        cl = new Clientes();
        conp = new ProductosJpaController();
        cf = new FacturaJpaController();
        fr = new Factura();
        pr = new Productos();
        control = new ClientesJpaController();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        usu = u;
        n = new Factura();
        cp = new ProductoVentaJpaController();

    }

    public void agregarregistro(long IdFactura, int cl, String nombre, int Producto, String detalle, Date fec, int cantidad, int precio, int subtotal, float iva, int total) {
        Object fila[] = {IdFactura, cl, nombre, Producto, detalle, fec, cantidad, precio, subtotal, iva, total};
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(fila);
        vector.add(fila);
    }

    public boolean ValidarCampo() {
        if (txt_code.getText().equals("")) {
            txt_code.requestFocus();
            return true;
        }
        if (txt_nom.getText().equals("")) {
            txt_nom.requestFocus();
            return true;
        }
        if (txt_cant.getText().equals("")) {
            txt_cant.requestFocus();
            return true;
        }
        if (txt_pro.getText().equals("")) {
            txt_pro.requestFocus();
            return true;
        }
        if (txt_cliente.getText().equals("")) {
            txt_cliente.requestFocus();
            return true;
        }
        return false;
    }

    public void LimpiarCampos() {
        txt_pro.setText(null);
        txt_cant.setText(null);
        txt_pro.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_code = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        txt_pro = new javax.swing.JTextField();
        Buscar_cliente = new javax.swing.JButton();
        buscar_producto = new javax.swing.JButton();
        txt_cant = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/invoice_951764.png"))); // NOI18N
        jLabel12.setText("Factura");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 366, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Id Factura");

        txt_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_clienteKeyTyped(evt);
            }
        });

        jLabel3.setText("Cliente");

        jLabel4.setText("Nombre");

        jLabel5.setText("producto");

        txt_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codeKeyTyped(evt);
            }
        });

        txt_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomKeyTyped(evt);
            }
        });

        txt_pro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_proKeyTyped(evt);
            }
        });

        Buscar_cliente.setBackground(new java.awt.Color(136, 212, 234));
        Buscar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/lupa.png"))); // NOI18N
        Buscar_cliente.setText("Search");
        Buscar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_clienteActionPerformed(evt);
            }
        });

        buscar_producto.setBackground(new java.awt.Color(136, 212, 234));
        buscar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/lupa.png"))); // NOI18N
        buscar_producto.setText("Search");
        buscar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_productoActionPerformed(evt);
            }
        });

        txt_cant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantActionPerformed(evt);
            }
        });
        txt_cant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantKeyTyped(evt);
            }
        });

        jLabel6.setText("Cantidad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_pro)
                                    .addComponent(txt_nom))))
                        .addGap(55, 55, 55)))
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscar_producto, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(Buscar_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_cant, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar_cliente))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar_producto))
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton3)
                .addGap(43, 43, 43)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 360, 60));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id factura", "Cliente", "Nombre", "Producto", "Detalle", "Fecha", "Cantidad", "Precio", "Subtotal", "IVA", "Total"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 680, 214));

        jPanel4.setBackground(new java.awt.Color(136, 212, 234));

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/city.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 300, 780));

        jLabel7.setBackground(new java.awt.Color(136, 212, 234));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/city.png"))); // NOI18N
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 500));

        jPanel5.setBackground(new java.awt.Color(136, 212, 234));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 280));

        jPanel6.setBackground(new java.awt.Color(136, 212, 234));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 680, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Buscar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_clienteActionPerformed
        // TODO add your handling code here:
        Busqueda_clientes n = new Busqueda_clientes((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true, txt_cliente, txt_nom);
        n.setVisible(true);
        txt_nom.setEnabled(false);
        txt_cliente.setEnabled(false);

    }//GEN-LAST:event_Buscar_clienteActionPerformed

    private void buscar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_productoActionPerformed
        // TODO add your handling code here:
        Busqueda_producto n = new Busqueda_producto((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true, txt_pro);
        n.setVisible(true);
        txt_pro.setEnabled(false);
    }//GEN-LAST:event_buscar_productoActionPerformed

    private void txt_cantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "empty table");
        } else {
            long id = Long.parseLong(txt_code.getText());
            facbus = cf.findFactura(id);
            if (facbus != null) {
                JOptionPane.showMessageDialog(this, "Numero de factura Existente , Cambie el numero de factura");
            } else {
                LocalDate fechaloc = LocalDate.now();
                Date fechaact = Date.from(fechaloc.atStartOfDay(ZoneId.systemDefault()).toInstant());
                java.sql.Date fechaingre = new java.sql.Date(fechaact.getTime());
                n.setIdfactura(id);
                n.setFecha(fechaingre);
                int cedula = Integer.parseInt(txt_cliente.getText());
                cl = control.findClientes(cedula);
                n.setClientesCedula(cl);
                n.setUsuarioIdusuario(usu);
                try {
                    cf.create(n);
                    for (int i = 0; i < vector.size(); i++) {
                        ProductoVenta m = new ProductoVenta();
                        int producto = (Integer) jTable1.getValueAt(i, 3);
                        long ide = Long.parseLong(txt_code.getText());
                        pr = conp.findProductos(producto);
                        m.setProductosCodigo(pr);
                        Factura me = new Factura();
                        me = cf.findFactura(ide);
                        m.setFacturaIdfactura(me);
                        int cantidad = (int) jTable1.getValueAt(i, 6);
                        m.setCantidad(cantidad);
                        cp.create(m);
                    }
                    JOptionPane.showMessageDialog(this, "Record saved successfully");
                    DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
                    mod.setRowCount(0);
                } catch (Exception ex) {
                    Logger.getLogger(Form_Factura.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (ValidarCampo()) {
            JOptionPane.showMessageDialog(this, "empty field");
        } else {
            long id = Long.parseLong(txt_code.getText());
            facbus = cf.findFactura(id);
            if (facbus != null) {
                JOptionPane.showMessageDialog(this, "Numero de factura Existente , Cambie el numero de factura");
            } else {
                String nombre = txt_nom.getText();
                LocalDate fechaloc = LocalDate.now();
                Date fechaact = Date.from(fechaloc.atStartOfDay(ZoneId.systemDefault()).toInstant());
                java.sql.Date fechaingre = new java.sql.Date(fechaact.getTime());
                n.setFecha(fechaingre);
                int cedula = Integer.parseInt(txt_cliente.getText());
                cl = control.findClientes(cedula);
                n.setClientesCedula(cl);
                n.setUsuarioIdusuario(usu);
                int pro = Integer.parseInt(txt_pro.getText());
                int cantidad = Integer.parseInt(txt_cant.getText());
                pr = conp.findProductos(pro);
                int subtotal = pr.getPrecioUnitario() * cantidad;
                float iva = (float) (subtotal * 0.19);
                int total = (int) (subtotal + iva);
                agregarregistro(id, cl.getCedula(), nombre, pr.getCodigo(), pr.getNombre(), fechaact, cantidad, pr.getPrecioUnitario(), subtotal, iva, total);
                LimpiarCampos();

            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codeKeyTyped
        // TODO add your handling code here:
        int tecla = evt.getKeyChar();
        if (!(tecla > 47 && tecla < 58)) {
            evt.consume();
        }
        if (txt_code.getText().trim().length() > 10) {
            JOptionPane.showMessageDialog(this, "Cantidad maxima 99999999999 excedida");
            evt.consume();
        }
    }//GEN-LAST:event_txt_codeKeyTyped

    private void txt_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_clienteKeyTyped
        // TODO add your handling code here:
        int tecla = evt.getKeyChar();
        if (!(tecla > 47 && tecla < 58)) {
            evt.consume();
        }
        if (txt_cliente.getText().trim().length() > 6) {
            JOptionPane.showMessageDialog(this, "Numero Errado");
            evt.consume();
        }
    }//GEN-LAST:event_txt_clienteKeyTyped

    private void txt_proKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_proKeyTyped
        // TODO add your handling code here:
        int tecla = evt.getKeyChar();
        if (!(tecla > 47 && tecla < 58)) {
            evt.consume();
        }
        if (txt_pro.getText().trim().length() > 9) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Numero Extenso");
        }
    }//GEN-LAST:event_txt_proKeyTyped

    private void txt_cantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantKeyTyped
        // TODO add your handling code here:
        int tecla = evt.getKeyChar();
        if (!(tecla > 47 && tecla < 58)) {
            evt.consume();
        }
        if (txt_cant.getText().trim().length() > 2) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Cantidad maxima 999 Unidades");
        }
    }//GEN-LAST:event_txt_cantKeyTyped

    private void txt_nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomKeyTyped
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();

        if (!Character.isLetter(tecla)) {
            evt.consume(); // Consumir el evento si no es una letra
        }
    }//GEN-LAST:event_txt_nomKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Factura dialog = new Form_Factura(new javax.swing.JFrame(), true, new Usuario());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar_cliente;
    private javax.swing.JButton buscar_producto;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_cant;
    private javax.swing.JTextField txt_cliente;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_pro;
    // End of variables declaration//GEN-END:variables
}
